# 服务器相关
server:
  port: 8080

# spring相关
spring:
  application:
    name: cikp-mall
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://10.0.81.118:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hedl92ddd!@#d
  redis:
    host: 10.0.81.118 # Redis服务器地址 localhost
    database: 3 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 85a74071cb32dae6b860d3b96c15fe54 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  elasticsearch:
    rest:
      uris: https://10.0.81.118:9200
      username: elastic
      password: tophant_017
      read-timeout: 10s
  data:
    elasticsearch:
      repositories:
        enabled: true


# mybatis相关
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath*:com/**/mapper/*.xml

########################## 自定义配置 ##########################
# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

#es证书位置
esCert: D:/es/ca.crt

